Add test requirements including minimal versions
c4urself/bump2version pull request #143
Opened 2020-05-21 12:07 UTC by sebix

2020-05-21 13:44 UTC, ekohl commented on setup.py
> +    tests_require=[
This is deprecated since setuptools 41.5.0 per https://github.com/pypa/setuptools/pull/1878

2020-08-31 15:06 UTC, ekohl commented
Any thoughts on this? I also think that 6.0.0 is not entirely correct. From the changelog:
> LogCapture.actual() is now part of the documented public interface.

However, the class is much older. 1.2.0 mentions that `LogCapture` can now do some things, which means the class has always been there.

I think this can be closed.

2020-08-31 15:06 UTC, ekohl requested changes
Marking as changes required to indicate it's been reviewed.

2021-01-18 10:28 UTC, florisla commented
The preferred way to do this in `setup.py` is to use `extras_require`.

    extras_require={
        'test': ['pytest>=3.4.0']
    }

2021-01-18 21:14 UTC, sebix commented
As requested, I changed the testfixtures version to 1.2.0 and `tests_require` to `extras_require`

2021-01-21 21:37 UTC, florisla commented
Hi,

The required version of `testfixtures` in `tox.ini` differs versus `setup.py`. Any particular reason?

Could you squash your three commits into one? We don't need the `test_require` commits.

2021-01-21 21:41 UTC, florisla commented
I'm OK with putting this 'feature' in.

It's not the official testing strategy (that's Tox, and CI) but this is more light-weight and can be handy for contributors.

2021-01-24 19:59 UTC, sebix commented
I think I incorporated all requested changes now

2021-01-25 08:04 UTC, florisla commented
Thanks!

2021-01-25 09:40 UTC, ekohl commented on setup.py
> +                 ],
Nit: I'd prefer to format this similar to other lines
```suggestion
        'test': [
          'testfixtures>=1.2.0',
          'pytest>=3.4.0',
        ],
```

2021-01-25 21:29 UTC, merged