Test against python 3.9
c4urself/bump2version pull request #226
Opened 2021-08-12 11:12 UTC by clbarnes

A very minor update to be pushed through the CI sausage machine.

2021-08-18 13:34 UTC, florisla commented
Very nice, thanks! I put this on my list to review soon(*).

(*) Might not be really soon.

2021-08-18 14:57 UTC, clbarnes commented
This will probably be superceded by #229 .

2021-08-18 15:28 UTC, clbarnes commented
I reverted the 3.9 addition to that PR, and so will open a fresh one once that's merged.

2022-02-25 19:35 UTC, florisla requested changes
Needs a rebase now that we use Github Actions.

2022-02-25 19:35 UTC, florisla commented on README.md
> +* supports non-EOL Python (>=3.6 at time of writing) and PyPy3
Any particular reason to stop testing 3.5?  It's EOL at Python.org but some long-term-support distros might still support it.

Of course, enabling f-strings counts as a good reason ;-)

2022-02-26 17:06 UTC, closed without merging